name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Portfolio/Portfolio.Web/Portfolio.Web.csproj

    - name: Build
      run: dotnet build --configuration Release ./Portfolio/Portfolio.Web/Portfolio.Web.csproj

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish ./Portfolio/Portfolio.Web/Portfolio.Web.csproj

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/wwwroot
